services:

  builder:
    env_file:
      - path: .env.builder
        required: false
    privileged: true
    image: ghcr.io/ubuntu-gnome-remix/iso-builder:1.0.2
    volumes:
      - ./:/workspace/
    working_dir: /workspace
